connectors:
  twitch:
    always-listening: true
    channel: ${TWITCH_CHANNEL}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    code: ${OAUTH_CODE}
    forward-url: ${NGROK_URL}
    redirect: http://localhost/
    websocket-lease-time: 14400
  websocket:
    bot-name: "notrexroof"
    connection-timeout: 10
    max-connections: 10
databases:
  redis:
    host: "redis"
    reconnect: true
logging:
  level: debug
skills:
  awards:
    path: /usr/src/app/skills/awards/
  font-change:
    max_font_size: 60
    min_font_size: 9
    path: /usr/src/app/skills/font-change/
  twitch-events:
    path: /usr/src/app/skills/twitch-events/
  popup:
    path: /usr/src/app/skills/popup/
  points:
    path: /usr/src/app/skills/points/
  reply:
    path: /usr/src/app/skills/reply/
  shoutout:
    path: /usr/src/app/skills/shoutout/
welcome-message: true
web:
  base-url: ${NGROK_URL}
