version: "3"

services:

  ngrok:
    image: "wernight/ngrok"
    command:
      - ngrok
      - http 
      - notrexroof:8080
      - -log=stdout

  notrexroof:
    image: "rexroof/notrexroof"
    env_file: .env
    depends_on:
      - "ngrok"
      - "redis"
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      # if changing apps, clean twitch refresh token with this command:
      #  docker-compose run notrexroof rm /root/.local/share/opsdroid/twitch.json
      - local-opsdroid:/root/.local/share/opsdroid/
      - /tmp/bottmp:/tmp/bottmp
      - /home/rex/.config/alacritty/alacritty.yml:/usr/src/app/alacritty.yml
      - ./skills:/usr/src/app/skills
      - /usr/local/bin/tmux:/usr/local/bin/tmux
      - /tmp/tmux-1000:/tmp/tmux-1000
      # - /tmp/obs-blastfile.txt:/usr/src/app/blastfile.txt

  redis:
    image: redis:6.2.1
    container_name: bot-redis
    ports: [ 6379 ]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

volumes:
  local-opsdroid:
  redis-data:
